### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by Daenyth**
- Add dep on `future` for compat
- Rewrite hand-made test runner with pytest fixtures
- All tests green on py27 and py35
- Add test dep on pytest_server_fixtures to automatically launch rethinkdb processes
- Tox config is fixed so `tox` runs all tests
- Readme probably could use updating with info on how to run

### CODE REVIEW

**Review by jeffsuarez — APPROVED** [review]
These changes all look reasonable to me. So, assuming you have tested them all, they should be good to merge.

**Comment by Daenyth** [comment]
The tests are all green on my machine. It should be possible for you to confirm by pulling the branch and running `tox`

**Comment by Daenyth** [comment]
I don't have merge or pypi permissions, so I'll need you to update it - I've included a version bump to setup.py so all that should be required is packaging + upload

**Comment by jeffsuarez** [comment]
tox doesn't work for me.

``` python
(mockthink)  jsuarez@jeff-asus  ~/code/mockthink   master  tox                                                                                                         (master|…)
GLOB sdist-make: /home/jsuarez/code/mockthink/setup.py
py27 py35 inst-nodeps: /home/jsuarez/code/mockthink/.tox/dist/mockthink-0.9.5.zip
ERROR: invocation failed (errno 2), args: ['/home/jsuarez/code/mockthink/.tox/py27 py35/bin/pip', 'install', '-U', '--no-deps', '/home/jsuarez/code/mockthink/.tox/dist/mockthink-0.9.5.zip'], cwd: /home/jsuarez/code/mockthink
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 39, in main
    retcode = Session(config).runcommand()
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 389, in runcommand
    return self.subcommand_test()
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 546, in subcommand_test
    self.installpkg(venv, path)
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 489, in installpkg
    venv.installpkg(path, action)
  File "/usr/local/lib/python2.7/dist-packages/tox/venv.py", line 252, in installpkg
    self._install([sdistpath], extraopts=extraopts, action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/venv.py", line 307, in _install
    action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/venv.py", line 280, in run_install_command
    self._pcall(argv, cwd=self.envconfig.config.toxinidir, action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/venv.py", line 385, in _pcall
    redirect=redirect, ignore_ret=ignore_ret)
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 140, in popen
    stdout=stdout, stderr=STDOUT)
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 228, in _popen
    stdout=stdout, stderr=stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Pull request merged**
